title = 'Fibonacci number'
timelimit = 2.0
forum = '#'

[[tests]]
    name = "example.in"
    number = 12
[[tests]]
    name = "random.cpp"
    number = 10

[params]
    N_MIN = 0
    N_MAX = 1000000000000000000
    MOD = 1000000007
