solution = "correct.cpp"
verify = 'verify.cpp'
timelimit = 2.0

[[tests]]
    Name = "example.in"
    Number = 2
[[tests]]
    Name = "random.cpp"
    Number = 10

[[solutions]]
    name = "wa.cpp"
    wrong = true
