title = '\(\sum_i \sum _ {i \lt j} \left( a_i - a_j \right)\)'
timelimit = 2.0
forum = '#'

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 10

[[soluitons]]
    name = "naive.cpp"
    allow_tle = true

[params]
    N_MIN = 0
    N_MAX = 100000
    X_MIN = -100000000
    X_MAX = 100000000
