title = '\(\sum \sum a_i a_j\)'
timelimit = 2.0
forum = '#'

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 10

[[solutions]]
    name = "naive.cpp"
    allow_tle = true

[params]
    N_MIN = 0
    N_MAX = 100000
    X_MIN = -1000000000
    X_MAX = 1000000000
    MOD = 998244353
