title = '\(n!\)'
timelimit = 2.0
forum = '#'

[[tests]]
    name = "example.in"
    number = 11
[[tests]]
    name = "random.cpp"
    number = 10

[params]
    N_MIN = 0
    N_MAX = 10000000
    MOD = 998244353
