title = '\(\sum \sum \lvert x_i - x_j \rvert\)'
timelimit = 2.0
forum = '#'

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 10

[params]
    N_MIN = 0
    N_MAX = 100000
    X_MIN = -100000000
    X_MAX = 100000000
