name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: yosupo06/library-checker-judge
          path: library-checker-judge
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: gen protoc
        run: |
          cd library-checker-judge/deploy &&
          ./gen_protoc.sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
          pip install --user -r library-checker-judge/deploy/requirements.txt
      - name: Run deploy.py
        run: |
          ulimit -s unlimited
          PYTHONPATH=. ./library-checker-judge/deploy/problems_deploy.py . \
            --host=apiv1.yosupo.jp --prod \
            --api-pass $API_PASS \
            --minio-host $MINIO_HOST \
            --minio-access $MINIO_ACCESS_KEY \
            --minio-secret $MINIO_SECRET_KEY \
            --minio-bucket $MINIO_BUCKET
        env:
          API_PASS: ${{ secrets.API_PASS }}
          MINIO_HOST: ${{ secrets.MINIO_HOST }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_BUCKET: ${{ secrets.MINIO_BUCKET }}
