name: GeneratePy

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  generate-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Run generate_test.py
        run: |
          ulimit -s unlimited
          ./generate_test.py

  generate-test-without-colorlog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user toml markdown jinja2
      - name: Run generate_test.py
        run: |
          ulimit -s unlimited
          ./generate_test.py
