name: CI

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  generate-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.5.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Run generate_test.py
        run: |
          ulimit -s unlimited
          ./generate_test.py
        
  clang:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.5.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Install libc++-abi
        run: |
          apt-get install -y libc++-dev libc++abi-dev
      - name: Run generate.py on clang
        run: |
          ulimit -s unlimited
          ./generate.py problems.toml --verify --sol
        env:
          CXX: clang++
          CXXFLAGS: -O2 -std=c++14 -stdlib=libc++ -Wall -Wextra -Werror
