name: CI

on:
  push:
    branches: 
      - master
      - windows
  pull_request:

jobs:
  generate-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.5.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Run generate_test.py
        run: |
          ulimit -s unlimited
          ./generate_test.py
        
  clang-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.5.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Run generate.py on clang
        run: |
          ./ci_generate.py
        env:
          CXX: clang++
        uses: actions/cache@v1
        with:
          path: ~/generated.json
          key: ${{ runner.os }}-build
          restore-keys: ${{ runner.os }}-build

  gcc-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.5.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Run generate.py on gcc
        run: |
          ulimit -s unlimited
          ./ci_generate.py --htmldir=/tmp/html
        uses: actions/cache@v1
        with:
          path: ~/generated.json
          key: ${{ runner.os }}-build
          restore-keys: ${{ runner.os }}-build
      - name: Archive problem statements
        uses: actions/upload-artifact@v1
        with:
          name: statements
          path: /tmp/html

  mingw-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.5.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Run generate.py on gcc
        run: |
          python ci_generate.py --html --htmldir=D:/tmp/html
        uses: actions/cache@v1
        with:
          path: ~/generated.json
          key: ${{ runner.os }}-build
          restore-keys: ${{ runner.os }}-build
