name: Parallel

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  gcc-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Print problem list
        run: |
          ./ci_generate_parallel.py --show-list 5 ${{ matrix.id }}
      - name: Run generate.py on gcc
        run: |
          ulimit -s unlimited
          ./ci_generate_parallel.py 5 ${{ matrix.id }} --htmldir=/tmp/html

  mingw-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        id: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Print problem list
        run: |
          python ci_generate_parallel.py --show-list 5 ${{ matrix.id }}
      - name: Run generate.py on gcc
        run: |
          python ci_generate_parallel.py 5 ${{ matrix.id }} --htmldir=D:/tmp/html
